### ISSUE TITLE
Ignore 'Desktop.ini' files in folders

### ISSUE THREAD

**Issue by emelleby** [joakin/markdown-folder-to-html#18]
When you are running this on a windows machine then it will throw an error because Windows will create a desktop.ini file in each folder every time it is edited. This will stop markdown-folder-to-html from progessing. Can the file be ignored?

![image](https://user-images.githubusercontent.com/7002436/41611626-b3d8eeb8-73f0-11e8-8286-433f235bcf28.png)

**Comment by joakin** [comment]
This shouldn't be a problem. We are recursively copying everything so the file specifically shouldn't matter. See https://github.com/joakin/markdown-folder-to-html/blob/master/cli.js#L50

Some things that could help diagnose:

Maybe the output folder wasn't created (`_Stories`) and that's why the copy is failing.

Do you have a `_Stories` folder after the error? (even if empty).

Does it work if you rename `Stories` to `docs` and just run `markdown-folder-to-html`?

**Comment by emelleby** [comment]
Thanks for your swift reply and a great tool.

The folder is created but it does not convert any more files after the
error. so a lot does not get processed. If I delete all the desktop.ini
files before I run 'markdown-folder-to-html' then everything runs smooth.

I have not done the renaming to 'docs'. I don't see how that will affect it
but I can always try.

**Comment by joakin** [comment]
I've updated the dependencies, particularly shelljs which does the copying, in the last version.

Could you try with 2.0.1 and see if it is still happening?

Thanks!

**Comment by emelleby** [comment]
Hi,
How can I see my installed version and how do I update?

**Comment by joakin** [comment]
This should tell you the current version installed: `npm ls -g markdown-folder-to-html`

You can get the last one with `npm install -g markdown-folder-to-html@latest`

Remove `-g` if you have it installed locally on a project folder instead of globally

**Comment by emelleby** [comment]
I must have upgraded in June to the 1.8.0 version. The 'contents.json' file
was already included and it did not throw the desktop.ini error.

Now I have upgraded to 2.1.1 which seems to work perfectly at first glance.

Thanks for providing this tool and improving it.

For the request list, it would be good to have a collapsible menu like
this: https://codepen.io/kojiroh/pen/foAFb

Cheers
Eivind

**Comment by joakin** [comment]
Cool, good to hear! 👍

**Comment by joakin** [comment]
Oh damn it. That sucks.

I can't help with this because of time commitments. The thing to do is probably to make a small reproducible node.js example only using `shelljs` and posting a bug to that repo to see if they can copy it.

Luckily there is a workaround like you mentioned before.
