### ISSUE TITLE
sidebar NAV

### ISSUE THREAD

**Issue by lwasylow** [joakin/markdown-folder-to-html#21]
Hi 
I believe the  render-nav.js should be slightly changed to cater for nested options.
closing LI should be moved at the end of parent (dir)
in line 

```js
if (f.type === "dir") {
            const childrenNav = renderNav(f.children, level + 1);
            const indexFile = getIndexFile(f.children);
            // Heading with link if there is an index file in the folder
            if (indexFile) {
                const link = renderActive(f.name, indexFile.value.href, indexFile.value.active);
                return `<li class="heading">${link}\n${childrenNav}\n</li>`;
            }
            // Heading without link
            return `<li class="heading"><span>${f.name}</span></li>\n${childrenNav}\n</li>`;
        }
```
that way you can easily add dropdown menu as well.

**Comment by joakin** [comment]
CSS has the `+` (adjacent siblinb) selector [mdn docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator) so it is possible to make dropdown/collapsible folders with browser JS with the current HTML structure. No need to change the HTML generation IMO.
