### ISSUE TITLE
Add ability to print a "generated at {}" at the bottom

### ISSUE THREAD

**Issue by Firesphere** [joakin/markdown-folder-to-html#31]
I've been trying a few things, but I'd like to be able to add a "generated at {date time} at the bottom of each page. So I can make sure that the latest docs are indeed properly generated.

**Comment by joakin** [comment]
Adding JS templating is out of scope right now although it is something I've considered from time to time, being able to accept a template.ejs as well as a template.html

For now though, you may be able to use a [custom HTML template](https://github.com/joakin/markdown-folder-to-html#custom-html) or copy the [default one](https://github.com/joakin/markdown-folder-to-html/blob/master/docs/template.html) and add a snippet of browser side JS to fetch the same file you are on and look at the response headers. For example GitHub pages serves this header:

```
Last-Modified: Fri, 23 Aug 2019 09:48:14 GMT
```

That you can put on the HTML with JS.

I'll keep your use case in mind when considering adding more flexible templating in a future version.
