### ISSUE TITLE
Allow for spaces in image filenames

### ISSUE THREAD

**Issue by StruffelProductions** [joakin/markdown-folder-to-html#40]
When working with Typora (my markdown editor) the following markdown code renders as expected:
```
![img/Untitled 19.png](img/Untitled 19.png)
![img/Untitled 20.png](img/Untitled 20.png)
```
However, after running markdown-folder-to-html on it, the images are not displayed:
![image](https://user-images.githubusercontent.com/31403260/119239457-7ed7a300-bb49-11eb-8ae4-88a6ec6d8d19.png)

I instead have to manually adjust the links like this:
```
![img/Untitled 19.png](img/Untitled%2019.png)
![img/Untitled 20.png](img/Untitled%2020.png)
```
to actually get the images to show up as expected.

This is a really annoying issue since it can't even be caught by parsing the page with a testing tool since there isn't actually a missing image in the HTML, the testing tool just sees the text and assumes that nothing is missing.

**Comment by joakin** [comment]
Hi hi!

I've googled around and it seems like URLs on images that aren't encoded, like your `img/Untitled 19.png`, aren't valid markdown.

This project uses markdown-it, and I found this issue from a few years ago with someone that had the same problem:

https://github.com/markdown-it/markdown-it/issues/162

> Url-escaping the url works just fine:
> 
> ```markdown
> ![local image](rattlesnake%20image.jpg)
> ```
> 
> Alternatively, you can enclose url in angular brackets, which will allow wider range of characters in it including spaces:
> 
> ```markdown
> ![local image](<rattlesnake image.jpg>)
> ```
> 
> So, it's not a bug. You can also check [commonmark spec](http://spec.commonmark.org/0.22/#link-destination) for more details on which characters are accepted in the link destination.

[Example from the markdown-it playground](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5Cn!%5Bimg%2FUntitled%2020.png%5D%28img%2FUntitled%2020.png%29%5Cn%5Cn!%5Bimg%2FUntitled%2020.png%5D%28img%2FUntitled%252020.png%29%5Cn%5Cn!%5Bimg%2FUntitled%2020.png%5D%28%3Cimg%2FUntitled%2020.png%3E%29%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

It seems like Typora is doing some non-standard things with markdown :( Sadly these days with all of the new age markdown editors and wikis there is a lot of extending markdown with custom features that aren't standard, and that will create a lot of compatibility problems in the future.

Let me know if these solutions are acceptable to you.

And thanks for cc0textures! I used it a few months ago to sketch a 3d environment and it was super helpful! ♥

**Comment by StruffelProductions** [comment]
I actually just checked the Typora settings again. It does have the option for url encoding. It's just off be default. Thanks for the tool!

**Comment by joakin** [comment]
Awesome, great to hear :D
