### ISSUE TITLE
table not support ? 

### ISSUE THREAD

**Issue by mudenglong** [joakin/markdown-folder-to-html#8]
can't parse string like this: 

```
| col1  | col2 | col3 |
|---------|----------------|----------------|
| 1111   | 22222 | 3333 |
```

I found the package which parse markdown to html named "commonmark" .
There's a discussion forum for this: https://talk.commonmark.org/t/tables-in-pure-markdown/81. 

Is there any plan to support "table" ?

**Comment by joakin** [comment]
Ye this is something I've wanted to support/have.

I've switched the parser to markdown-it which better supports github flavored markdown. Seems like the spec compliant commonmark is a bit stale.

So now tables and auto-link are enabled. I've [released v1.5.1](https://github.com/joakin/markdown-folder-to-html/compare/v1.4.4...v1.5.1), see http://chimeces.com/markdown-folder-to-html/1-banana.html for the example output!
